/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/coolGallery.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.53}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-4.05, 0.02, 4.24]} rotation={[2.38, 0.63, -2.79]}>
            <mesh geometry={nodes.Object_6.geometry} material={materials.WoodFloor} />
          </group>
          <group position={[-4.05, 0.02, 4.24]} rotation={[2.38, 0.63, -2.79]}>
            <mesh geometry={nodes.Object_4.geometry} material={materials.PixelPallete} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/coolGallery.glb')
