/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Marcin Lubecki (https://sketchfab.com/Lubus)
license: SKETCHFAB Editorial (https://sketchfab.com/licenses)
source: https://sketchfab.com/3d-models/vr-game-hub-lobby-4k-a52a916abfa94e71ad9600c1b87e2e05
title: VR Game Hub Lobby 4k
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/lobby.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.02}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[220.82, 0, 9.8]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes["floor_Material_#727_0"].geometry}
              material={materials.Material_727}
            />
          </group>
          <group position={[-68.55, 0, 149.95]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes["walls_Material_#723_0"].geometry}
              material={materials.Material_723}
            />
          </group>
          <group position={[220.82, 0, 9.8]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes["window_Material_#1_0"].geometry}
              material={materials.Material_1}
            />
          </group>
          <group position={[220.82, 0, 9.8]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.glass_Glass_Clear_0.geometry}
              material={materials.Glass_Clear}
            />
          </group>
          <group position={[220.82, 0, 9.8]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes["ground_Material_#724_0"].geometry}
              material={materials.Material_724}
            />
          </group>
          <group
            position={[232.15, -7.37, 51.92]}
            rotation={[-0.64, 0.11, 0.82]}
          >
            <mesh
              geometry={nodes.grass__0.geometry}
              material={materials.grass__0}
            />
          </group>
          {/* <group position={[-74.46, 117.14, -88.62]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes['interior_Material_#726_0'].geometry} material={materials.Material_726} />
          </group> */}
          <group position={[234.7, 410.21, 14.76]} rotation={[-Math.PI, 0, 0]}>
            <mesh
              geometry={nodes.leaf_elm_leaf_0.geometry}
              material={materials.elm_leaf}
            />
          </group>
          <group position={[229.95, 332.73, 11.11]} rotation={[-Math.PI, 0, 0]}>
            <mesh
              geometry={nodes["Tree_Material_#732_0"].geometry}
              material={materials.Material_732}
            />
          </group>
          <group position={[220.82, 0, 9.8]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes["celling_Material_#733_0"].geometry}
              material={materials.Material_733}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/lobby.glb");
