/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/lowPolyDesk.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-2.96, 1.46, -1.59]} scale={[0.44, 1, 1.09]}>
            <mesh geometry={nodes.Mesh_10.geometry} material={nodes.Mesh_10.material} />
            <mesh geometry={nodes.Mesh_11.geometry} material={nodes.Mesh_11.material} />
            <mesh geometry={nodes.Mesh_9.geometry} material={nodes.Mesh_9.material} />
          </group>
          <group position={[0.89, 1.04, -1.68]} rotation={[1.44, 0, -Math.PI / 2]} scale={[-0.23, -0.04, -0.23]}>
            <mesh geometry={nodes.Mesh_12.geometry} material={nodes.Mesh_12.material} />
            <mesh geometry={nodes.Mesh_13.geometry} material={materials.blue} />
          </group>
          <group position={[-0.9, 0.47, -0.43]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-1.41, -0.02, -0.42]}>
            <mesh geometry={nodes.Mesh_5.geometry} material={nodes.Mesh_5.material} />
            <mesh geometry={nodes.Mesh_6.geometry} material={nodes.Mesh_6.material} />
          </group>
          <group position={[-0.91, 0.55, -1.55]} scale={[0.52, 0.1, 0.34]}>
            <mesh geometry={nodes.Mesh_2.geometry} material={materials['7355608']} />
            <mesh geometry={nodes.Mesh_3.geometry} material={nodes.Mesh_3.material} />
            <mesh geometry={nodes.Mesh_4.geometry} material={nodes.Mesh_4.material} />
          </group>
          <group position={[0.79, 0.47, -0.78]} scale={[0.11, 0.11, 0.2]}>
            <mesh geometry={nodes.Mesh_7.geometry} material={nodes.Mesh_7.material} />
            <mesh geometry={nodes.Mesh_8.geometry} material={nodes.Mesh_8.material} />
          </group>
          <group position={[0.71, 0.47, -0.75]} scale={0.58}>
            <mesh geometry={nodes.Mesh_14.geometry} material={nodes.Mesh_14.material} />
            <mesh geometry={nodes.Mesh_15.geometry} material={nodes.Mesh_15.material} />
          </group>
          <group position={[-1.15, -2.84, -1.51]} scale={[1, 1, 0.88]}>
            <mesh geometry={nodes.Mesh_0.geometry} material={materials['Material.003']} />
            <mesh geometry={nodes.Mesh_1.geometry} material={nodes.Mesh_1.material} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/lowPolyDesk.glb')
