/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/workspace.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.04}>
        <group position={[-582.29, -325.02, -227.88]}>
          <mesh geometry={nodes.Mesh_0.geometry} material={materials['05___Default']} />
          <mesh geometry={nodes.Mesh_1.geometry} material={materials['11___Default']} />
          <mesh geometry={nodes.Mesh_2.geometry} material={materials.Laptop} />
          <mesh geometry={nodes.Mesh_3.geometry} material={materials.Laptop2} />
          <mesh geometry={nodes.Mesh_4.geometry} material={materials['04___Default']} />
          <mesh geometry={nodes.Mesh_5.geometry} material={materials['06___Default']} />
          <mesh geometry={nodes.Mesh_6.geometry} material={materials['07___Default']} />
          <mesh geometry={nodes.Mesh_7.geometry} material={materials['08___Default']} />
          <mesh geometry={nodes.Mesh_8.geometry} material={materials['09___Default']} />
          <mesh geometry={nodes.Mesh_9.geometry} material={materials['10___Default']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/workspace.glb')
