/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_16: THREE.Mesh
    Object_4: THREE.Mesh
    Object_8: THREE.Mesh
    Object_12: THREE.Mesh
    Object_14: THREE.Mesh
  }
  materials: {
    concreto2: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ['Iron01.001']: THREE.MeshStandardMaterial
    piso: THREE.MeshStandardMaterial
    concrete3: THREE.MeshStandardMaterial
  }
}

export default function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/spacesOffice.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-22.75, 0.47, 10.79]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.09, 0.07, 0.09]}>
            <mesh geometry={nodes.Object_16.geometry} material={materials.concreto2} />
          </group>
          <group position={[-22.75, 0.47, 10.79]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.09, 0.07, 0.09]}>
            <mesh geometry={nodes.Object_4.geometry} material={materials['Material.001']} />
          </group>
          <group position={[-22.75, 0.47, 10.79]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.09, 0.07, 0.09]}>
            <mesh geometry={nodes.Object_8.geometry} material={materials['Iron01.001']} />
          </group>
          <group position={[-22.75, 0.47, 10.79]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.09, 0.07, 0.09]}>
            <mesh geometry={nodes.Object_12.geometry} material={materials.piso} />
          </group>
          <group position={[-22.75, 0.47, 10.79]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.09, 0.07, 0.09]}>
            <mesh geometry={nodes.Object_14.geometry} material={materials.concrete3} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/spacesOffice.glb')
